name: Todo-Counter
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            github_token: '${{ secrets.GITHUB_TOKEN }}'
            branch: '${{ github.ref }}'

      - name: install dependencies
        run: npm install
      - name: get current todos and update todo counter
        run: |
          npm run updateTodos
          echo "Pushing commit to the remote in the workflow" >> README.md

          git add -A
          git commit -m "Main workflow - updates README.md"
          git push