name: Release Package

on:
  push:
    branches:
      - master

jobs:
  release_package:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
