name: ci
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        run: npm install
      - name: Lint
        run: npm run lint
  tests:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test 🧪
        run: npm run test
