name: trigger-addTodos
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install
      - name: add todos to .js files
        run: |
          npm run addTodos
          echo "Pushing commit to the remote in the workflow"

          git config user.email "pushworkflow@example.com"
          git config user.name "main.yml"
          git add -A
          git commit -m "Main workflow - updates README.md"
          git push
      - name: get current todos and update todo counter
        run: npm run updateTodos
        run: |
          npm run updateTodos
          echo "Pushing commit to the remote in the workflow"

          git config user.email "pushworkflow@example.com"
          git config user.name "main.yml"
          git add -A
          git commit -m "Main workflow - updates README.md"
          git push