name: trigger-resetTodos
on:
  schedule:
      - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install
      - name: reset todos to .js files
        run: npm run resetTodos
      - name: get current todos and update todo counter
        run: npm run updateTodos
      - name: Commit any file changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: trigger-resetTodos action - Updated
          branch: master
          file_pattern: test/*.js README.md